version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ./drupal:/var/www/html
    expose:
      - 9000
    user: "1000:1000"

  nginx:
    build:
      context: .
      dockerfile: ./nginx/
    ports:
      - "80:80"
    volumes:
      - ./drupal:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - php

  mysql:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: drupal@@11
      MYSQL_DATABASE: drupal
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
