---
# Ansible playbook for a Drupal LAMP server.
#
# @author Jeff Geerling (2014).

- hosts: all
  gather_facts: true
  
  

  tasks:
    - name: Installation install software-properties-common
      apt: name=software-properties-common

    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

    - name: Add ondrej repository for later versions of PHP.
      apt_repository: repo='ppa:ondrej/php'

    - name: update after repo add
      apt:
        update_cache: yes

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - acl
          - git
          - unzip
          - sendmail
          - apache2
          - php8.2-common
          - php8.2-cli
          - php8.2-dev
          - php8.2-gd
          - php8.2-curl
          - php8.2-opcache
          - php8.2-xml
          - php8.2-mbstring
          - php8.2-pdo
          - php8.2-mysql
          - php8.2-apcu
          - libpcre3-dev
          - libapache2-mod-php8.2
          - python3-mysqldb
          - mysql-server
          - php8.3
        state: latest
        update_cache: true
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Configure Docker log driver
      lineinfile:
        path: /etc/docker/daemon.json
        line: '{"log-driver": "json-file", "log-opts": {"max-size": "100m"}}'
        create: yes

    - name: Set up Docker cron job for cleanup
      cron:
        name: "Docker Cleanup Job"
        minute: "0"
        hour: "10"
        job: "docker system prune -af"
